// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rdMzihQSZy3jhypjXvwdW_t9fUR0JBk',
    appId: '1:521844857787:web:b05f30b6eb4c84099ec29e',
    messagingSenderId: '521844857787',
    projectId: 'son-progress-meter',
    authDomain: 'son-progress-meter.firebaseapp.com',
    storageBucket: 'son-progress-meter.appspot.com',
    measurementId: 'G-GVBYM1WJ7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvxkkiuxFguTAqlBrj6UX5ME9bUOMSj4Y',
    appId: '1:521844857787:android:b36081ba47c1b61d9ec29e',
    messagingSenderId: '521844857787',
    projectId: 'son-progress-meter',
    storageBucket: 'son-progress-meter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHu6QZNi7sdE0GVVSvqUdAuESIfeTWLh0',
    appId: '1:521844857787:ios:d07d47639898d7349ec29e',
    messagingSenderId: '521844857787',
    projectId: 'son-progress-meter',
    storageBucket: 'son-progress-meter.appspot.com',
    iosBundleId: 'com.son.progressMeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHu6QZNi7sdE0GVVSvqUdAuESIfeTWLh0',
    appId: '1:521844857787:ios:d07d47639898d7349ec29e',
    messagingSenderId: '521844857787',
    projectId: 'son-progress-meter',
    storageBucket: 'son-progress-meter.appspot.com',
    iosBundleId: 'com.son.progressMeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6rdMzihQSZy3jhypjXvwdW_t9fUR0JBk',
    appId: '1:521844857787:web:d9a48d04e92a9e389ec29e',
    messagingSenderId: '521844857787',
    projectId: 'son-progress-meter',
    authDomain: 'son-progress-meter.firebaseapp.com',
    storageBucket: 'son-progress-meter.appspot.com',
    measurementId: 'G-WPJMQBPR86',
  );
}
